### ISSUE TITLE
Update Images for 2022 NEOs and Planet 9 Addons

### ISSUE THREAD

**Issue by Anthony-B-Russo10** [levinli303/celestia.mobi#16]
Image for Planet 9 Addon:
![Screen_Shot_2022-04-01_at_3 22 26_AM](https://user-images.githubusercontent.com/57239744/161216072-8d62502f-26d3-471a-9b7b-be0117e73eb3.png)

Image for 2022 NEOs Addon:
![earthand2022ff3](https://user-images.githubusercontent.com/57239744/161216159-c2858dbf-d13b-4d00-85a3-99c43650a767.jpg)

**Comment by levinli303** [comment]
please post updates in #14  and check the top post for the format of update
