### ISSUE TITLE
Class "diffuse" Objects are Visible/Ungrouped in Celestia Mobile's Browser

### ISSUE THREAD

**Issue by DaveBowman2001** [levinli303/celestia.mobi#18]
Regarding SpaceExplorer's [comment](https://github.com/levinli303/celestia.mobi/issues/17#issuecomment-1107855513) in #17, the names of objects defined as `Class "diffuse"` are cluttered outside any group in the Solar System Browser menu.
![Untitled](https://user-images.githubusercontent.com/99847641/164982404-d07c8320-6073-4876-bb69-3f4ea7bd6f25.jpg)

The names on arrows are meant to be the duplicates of `Class "spacecraft"` objects that act as their derelict/inactive remains. 3D surface features like [Olympus Mons](https://celestia.mobi/resources/item?item=DD817CE6-1703-B4CA-4177-FE653A57A310), and [Gale Crater](https://celestia.mobi/resources/item?item=2D583BD6-AF34-97CD-1242-C605A51B4970) addons are also defined as `Class "diffuse"` objects

If possible, we would like the names of `Class "diffuse"` objects be either grouped on their own (Diffuse) or not appear at all on the Browser itself

**Comment by levinli303** [comment]
I'll hide diffuse items from the browser, please also check this list and decide if any other should be hidden as well.

    enum
    {
        Planet         =    0x01,
        Moon           =    0x02,
        Asteroid       =    0x04,
        Comet          =    0x08,
        Spacecraft     =    0x10,
        Invisible      =    0x20,
        Barycenter     =    0x40, // Not used (invisible is used instead)
        SmallBody      =    0x80, // Not used
        DwarfPlanet    =   0x100,
        Stellar        =   0x200, // only used for orbit mask
        SurfaceFeature =   0x400,
        Component      =   0x800,
        MinorMoon      =  0x1000,
        Diffuse        =  0x2000,
        Unknown        = 0x10000,
    };

**Comment by DaveBowman2001** [comment]
I think "Component" should be hidden as well from the Browser, the rest are OK. Btw what does the "Unknown" category stand for?

**Comment by levinli303** [comment]
@DaveBowman2001 if not matching any of above, it is "unknown"

**Comment by DaveBowman2001** [comment]
Ahh...Gotcha

**Comment by levinli303** [comment]
Fixed in beta version of Celestia (Android/iOS/macOS), please test on the beta

**Comment by DaveBowman2001** [comment]
> Fixed in beta version of Celestia (Android/iOS/macOS), please test on the beta

I confirm! Names of diffuse and component-class objects are now hidden from the browser!
