### ISSUE TITLE
Editing and Replying to Specific Comments No Longer Possible

### ISSUE THREAD

**Issue by DaveBowman2001** [levinli303/celestia.mobi#31]
It's been 2 to 3 weeks now if I'm not mistaken, but on the Mobi Addons and even News Section, the ability of editing and replying to a specific comment seems to have been lost. Here's a sample screenshot below:
![image](https://user-images.githubusercontent.com/95486841/183295048-d78079a9-0bff-447d-983a-84ed40e96a3a.png)

**Comment by levinli303** [comment]
fixed by https://github.com/levinli303/celestia.mobi/commit/131444b461248baa7aa26a7971b6bb554f915411

**Comment by DaveBowman2001** [comment]
I confirm it is working! Thanks
