### ISSUE TITLE
Celestia.mobi comment impersonators.

### ISSUE THREAD

**Issue by Anthony-B-Russo10** [levinli303/celestia.mobi#41]
As noticed by a few users, Celestia.mobi's comment sections on some addons have some issues with people impersonating the addon developers.
This being an example of such, though to a more harmless degree.
![image](https://user-images.githubusercontent.com/57239744/197415271-fc6bd88f-32b7-4b6c-919e-3e2e8a180859.png)
Vs the actual comment I made (that the above was copied from).
![image](https://user-images.githubusercontent.com/57239744/197415356-b732b2c6-1135-405a-99d7-c1fa062b445f.png)

Why I am making this issues is based off of what SpaceExplorer mentioned in the Discord server on ways of dealing with this issue by either having usernames being verified or have a "loyalty seal" for verified addon developers.

**Comment by levinli303** [comment]
This would need require us to build a comment system and account system. or more accurately find instead of build since it would be complicated I'm definitely not building one from scratch.

**Comment by Anthony-B-Russo10** [comment]
Could possibly use some of the Forums account system to some degree.

**Comment by levinli303** [comment]
overall I think it is of very low priority before we find a comment system that satisfy all these requirements:

1. has an integrated account system that does not depend on social media account
2. can be deployed entirely locally
3. supports dark mode

now just report it by copying the link address of the post time.

**Comment by Anthony-B-Russo10** [comment]
> 3\. supports dark mode

The whole site could use it in general.

**Comment by SevenSpheres** [comment]
I think the point is that the site *does* support dark mode, so the comment system has to as well.

**Comment by Anthony-B-Russo10** [comment]
I haven't seen it, which could be due to it being more tied to the system's dark mode.

**Comment by DaveBowman2001** [comment]
> I think the point is that the site _does_ support dark mode, so the comment system has to as well.

I confirm this, but I only see this feature in mobile browsers and not on desktop browsers

**Comment by TheLostProbe** [comment]
i see it on both the mobile and desktop variants of firefox

**Comment by levinli303** [comment]
dark mode is supported only when both of the browser and the system supports dark mode. you can also force enabling it by adding `&theme=dark` to add-on pages.

**Comment by levinli303** [comment]
an update on this. I plan to find a github issue based comment widget. which requires the use of github sign-in to post comments.

**Comment by levinli303** [comment]
it will look like this:
https://utteranc.es

some notes:
existing comments will not be migrated (because existing comments do not have GitHub account associated)
in-app commenting will be disabled (as soon as you click sign in button, user will be taken outside of the app)

**Comment by DaveBowman2001** [comment]
Seems like the new commenting format is only visible in browser mode, and not on the app itself

In-App
![Screenshot_20230318-224930](https://user-images.githubusercontent.com/95486841/226113330-af4a3d9c-89af-480f-abd0-e38ee764ca4c.png)

Browser:
![Screenshot_20230318-225150](https://user-images.githubusercontent.com/95486841/226113406-1a70135f-435c-407f-b024-60636d03c857.png)

**Comment by levinli303** [comment]
> Seems like the new commenting format is only visible in browser mode, and not on the app itself
> 
> In-App ![Screenshot_20230318-224930](https://user-images.githubusercontent.com/95486841/226113330-af4a3d9c-89af-480f-abd0-e38ee764ca4c.png)
> 
> Browser: ![Screenshot_20230318-225150](https://user-images.githubusercontent.com/95486841/226113406-1a70135f-435c-407f-b024-60636d03c857.png)

This is a bug. The comment system depends on cookie to work, but I did not enable cookie in Android Celestia (on other platforms it is enabled). I've applied a workaround on enable it on Android to work without cookie (since it is readonly inapp, so cookie is not really useful). Should be able to see it now

**Comment by levinli303** [comment]
comments should be visible in app now.

**Comment by DaveBowman2001** [comment]
> comments should be visible in app now.

Yep, I can see it now as well
![Screenshot_20230319-004544](https://user-images.githubusercontent.com/95486841/226120966-2a15acbd-4d3c-489b-8246-26e4b0a9c67c.png)
> in-app commenting will be disabled (as soon as you click sign in button, user will be taken outside of the app

The `Sign-in with GitHub` button does take me outside the app while attempting to comment. It works well so far this time, probably best if we announce a guideline on how to use the new commenting system?

**Comment by levinli303** [comment]
I might move again to use [this](https://github.com/giscus/giscus) which is better localized and seems to support replies

**Comment by DaveBowman2001** [comment]
> migrated to giscus.

Replies are fully working
![Screenshot_20230320-212013-01](https://user-images.githubusercontent.com/95486841/226351384-f931f417-4bf9-431b-9b1c-7dc455c57a6e.jpeg)
