### ISSUE TITLE
celestia.cn selling fake star name certificate

### ISSUE THREAD

**Issue by levinli303** [levinli303/celestia.mobi#53]
This website https://www.celestia.cn is selling fake star name certificate, and uses Celestia as a way to show the certificate.

It seems they are selling fake star name certificates and offer download for an add-on that contains that star with an info link, on iOS/Android, Celestia fetches a preview of the link so it almost looked like it is built in feature to Celestia...

a screenshot from this website...
![1-210926235211U6](https://user-images.githubusercontent.com/17924287/215800023-499083f3-c7e8-4c90-84d6-1ddf2caf6dd2.png)

**Comment by DaveBowman2001** [comment]
Should I make a news article about that?

**Comment by SevenSpheres** [comment]
Celestia's website is [based on a template](https://github.com/CelestiaProject/Celestia/issues/1491), but actually looking at the celestia.cn website now, it's definitely copied from Celestia's website since it claims to be hosted by Fosshost.

**Comment by levinli303** [comment]
I'll make a news article when I got time

**Comment by levinli303** [comment]
I'll make one after I release 1.5.17

**Comment by levinli303** [comment]
I just let ChatGPT write it, a draft:

English:

Disclaimer: Celestia app is in no way affiliated with the website celestia.cn. We do not endorse or support any activities related to the sale of fake star name certificates or any other fraudulent activities. The website celestia.cn is not authorized to display any of its products or services in the Celestia app. Please exercise caution and conduct your own due diligence before engaging with any website or individual claiming to offer star naming services or other celestial-themed products.

Chinese:

免责声明：Celestia应用程序与celestia.cn网站没有任何关联。我们不认可或支持任何与售卖假星名证书或任何其他欺诈行为相关的活动。celestia.cn网站未经授权，不得在Celestia应用程序中展示任何其产品或服务。在与声称提供星座命名服务或其他天体主题产品的任何网站或个人进行交易前，请谨慎行事并进行自己的尽职调查。

**Comment by levinli303** [comment]
A revised version, again by ChatGPT

English:

Disclaimer: Please note that the practice of "naming" a star is not recognized by the scientific community, and the International Astronomical Union (IAU), the internationally recognized authority for assigning designations and names to celestial bodies, does not offer commercial star-naming services. Therefore, any star-naming services offered by private companies are not officially recognized and do not confer any legal or scientific validity.

In addition, we want to clarify that Celestia app is not affiliated with any of these companies or their star-naming services. While we have heard that some companies have been using Celestia to showcase their star name certificates, we do not endorse or support these services and are not associated with them in any way. Any information or claims related to these services that may appear in connection with Celestia app are not authorized by us and should be viewed with skepticism. Please exercise caution and conduct your own due diligence before engaging with any website or individual claiming to offer star-naming services or other celestial-themed products.

Chinese:

免责声明：请注意，将恒星命名为特定名称的做法不被科学界认可。国际天文学联合会（IAU）是国际公认的为天体指定编号和名称的权威机构，它不提供商业星座命名服务。因此，任何由私人公司提供的星座命名服务均未得到官方认可，不具有任何法律或科学有效性。

此外，我们想澄清的是，Celestia应用程序与这些公司或它们的星座命名服务没有任何关联。虽然我们听说有些公司一直在使用Celestia来展示他们的星座命名证书，但我们不认可或支持这些服务，也不与它们有任何关联。任何与Celestia应用程序相关的关于这些服务的信息或声明均未经我们授权，并应予以怀疑。在与声称提供星座命名服务或其他天体主题产品的任何网站或个人进行交易前，请谨慎行事并进行自己的尽职调查。

**Comment by SevenSpheres** [comment]
Looks good, except I'd remove
> the practice of "naming" a star is not recognized by the scientific community

since the scientific community *does* recognize star names, mainly those assigned by the IAU.

It might be worth linking to [the IAU's page on this topic](https://iau.org/public/themes/buying_star_names/).

**Comment by levinli303** [comment]
> Looks good, except I'd remove
> 
> > the practice of "naming" a star is not recognized by the scientific community
> 
> since the scientific community _does_ recognize star names, mainly those assigned by the IAU.
> 
> It might be worth linking to [the IAU's page on this topic](https://iau.org/public/themes/buying_star_names/).

great, updated in place in the comment.
