### ISSUE TITLE
SPICE trajectories no longer work

### ISSUE THREAD

**Issue by SpaceExplorer2008** [levinli303/celestia.mobi#55]
Hello 

Another bug that appeared in mobi due to the last update. SPICE trajectories no longer work, as they used to. If you want to test it, download the addons [65803 Didymos](https://celestia.mobi/resources/item?item=2A604656-CB13-4C35-956F-5F1BAE810396) and [DART](https://celestia.mobi/resources/item?item=35DD15C3-F872-8561-4302-45B7FD337221), respectively. Both use SPICE kernels, and they no longer appear in Celestia. Remembering that they have the correct IDs.

**Comment by SpaceExplorer2008** [comment]
Are the addons with SPICE broken or is it Celestia's code?

**Comment by levinli303** [comment]
Fixed in 1.5.19 (338)
