### ISSUE TITLE
Multiple Detail Images on Submitting Rich Descriptions No Longer Possible

### ISSUE THREAD

**Issue by DaveBowman2001** [levinli303/celestia.mobi#56]
There is a problem with uploading multiple `Detail Images`...only the first picture is uploaded and it just duplicates the rest:
This was actually first reported by **Anthony_B_Russo10** on Discord a few months ago, but I didn't realized back then that it is an actual bug

Examples:
**_[Hayabusa2](https://celestia.mobi/resources/item?item=133C0733-1699-7F0E-C7E5-AB2A2AC174B2)_**
![image](https://user-images.githubusercontent.com/95486841/228435347-da196385-83c8-46b7-a020-7f96a5d4e02e.png)

**_[Mars Rotovator](https://celestia.mobi/resources/item?item=26F9FF8A-21F5-401A-9DCC-C25334F294A1)_**
![image](https://user-images.githubusercontent.com/95486841/228434783-08b80103-9532-4391-a537-9c55d11c4ecb.png)

**_[Soyuz: 1986-Present](https://celestia.mobi/resources/item?item=DDA2419F-4714-43BE-8EC7-92B8D8DBDB45)_**
![image](https://user-images.githubusercontent.com/95486841/228434969-449541e2-2e76-458b-9e87-cac23172b1e7.png)

**Comment by levinli303** [comment]
should be fixed now, please test again.

**Comment by DaveBowman2001** [comment]
Yep...the detail images have been restored. Thanks!

Sample screenshot from [**Hayabusa2**](https://celestia.mobi/resources/item?item=133C0733-1699-7F0E-C7E5-AB2A2AC174B2)
![image](https://user-images.githubusercontent.com/95486841/228498672-d39f6235-0ba7-45b5-b734-8fcc08979fd4.png)
