### ISSUE TITLE
Upgrading server to Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by levinli303** [levinli303/celestia.mobi#58]
Current Ubuntu 18.04 LTS has reached end of life.

Need to update to 22.04 LTS, server will be down during upgrade.

**Comment by DaveBowman2001** [comment]
I'm curious, is the mobi itself going to be down while it is being updated to the new Ubuntu version?

**Comment by levinli303** [comment]
> I'm curious, is the mobi itself going to be down while it is being updated to the new Ubuntu version?

yes, i have not planned the exact time. but it should be a very brief down time if things go right.

**Comment by levinli303** [comment]
OK, i'll try to do it now that i've got some time

**Comment by levinli303** [comment]
Upgrade is completed.
